/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.ginema.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class DoubleEntry extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"DoubleEntry\",\"namespace\":\"com.ginema.avro\",\"fields\":[{\"name\":\"n\",\"type\":[\"string\",\"null\"]},{\"name\":\"v\",\"type\":\"double\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence n;
  @Deprecated public double v;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public DoubleEntry() {}

  /**
   * All-args constructor.
   */
  public DoubleEntry(java.lang.CharSequence n, java.lang.Double v) {
    this.n = n;
    this.v = v;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return n;
    case 1: return v;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: n = (java.lang.CharSequence)value$; break;
    case 1: v = (java.lang.Double)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'n' field.
   */
  public java.lang.CharSequence getN() {
    return n;
  }

  /**
   * Sets the value of the 'n' field.
   * @param value the value to set.
   */
  public void setN(java.lang.CharSequence value) {
    this.n = value;
  }

  /**
   * Gets the value of the 'v' field.
   */
  public java.lang.Double getV() {
    return v;
  }

  /**
   * Sets the value of the 'v' field.
   * @param value the value to set.
   */
  public void setV(java.lang.Double value) {
    this.v = value;
  }

  /** Creates a new DoubleEntry RecordBuilder */
  public static com.ginema.avro.DoubleEntry.Builder newBuilder() {
    return new com.ginema.avro.DoubleEntry.Builder();
  }
  
  /** Creates a new DoubleEntry RecordBuilder by copying an existing Builder */
  public static com.ginema.avro.DoubleEntry.Builder newBuilder(com.ginema.avro.DoubleEntry.Builder other) {
    return new com.ginema.avro.DoubleEntry.Builder(other);
  }
  
  /** Creates a new DoubleEntry RecordBuilder by copying an existing DoubleEntry instance */
  public static com.ginema.avro.DoubleEntry.Builder newBuilder(com.ginema.avro.DoubleEntry other) {
    return new com.ginema.avro.DoubleEntry.Builder(other);
  }
  
  /**
   * RecordBuilder for DoubleEntry instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<DoubleEntry>
    implements org.apache.avro.data.RecordBuilder<DoubleEntry> {

    private java.lang.CharSequence n;
    private double v;

    /** Creates a new Builder */
    private Builder() {
      super(com.ginema.avro.DoubleEntry.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.ginema.avro.DoubleEntry.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.n)) {
        this.n = data().deepCopy(fields()[0].schema(), other.n);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.v)) {
        this.v = data().deepCopy(fields()[1].schema(), other.v);
        fieldSetFlags()[1] = true;
      }
    }
    
    /** Creates a Builder by copying an existing DoubleEntry instance */
    private Builder(com.ginema.avro.DoubleEntry other) {
            super(com.ginema.avro.DoubleEntry.SCHEMA$);
      if (isValidValue(fields()[0], other.n)) {
        this.n = data().deepCopy(fields()[0].schema(), other.n);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.v)) {
        this.v = data().deepCopy(fields()[1].schema(), other.v);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'n' field */
    public java.lang.CharSequence getN() {
      return n;
    }
    
    /** Sets the value of the 'n' field */
    public com.ginema.avro.DoubleEntry.Builder setN(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.n = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'n' field has been set */
    public boolean hasN() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'n' field */
    public com.ginema.avro.DoubleEntry.Builder clearN() {
      n = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'v' field */
    public java.lang.Double getV() {
      return v;
    }
    
    /** Sets the value of the 'v' field */
    public com.ginema.avro.DoubleEntry.Builder setV(double value) {
      validate(fields()[1], value);
      this.v = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'v' field has been set */
    public boolean hasV() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'v' field */
    public com.ginema.avro.DoubleEntry.Builder clearV() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public DoubleEntry build() {
      try {
        DoubleEntry record = new DoubleEntry();
        record.n = fieldSetFlags()[0] ? this.n : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.v = fieldSetFlags()[1] ? this.v : (java.lang.Double) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
